export const contestData = [
  {
    sl: 1,
    contestID: "ABC123",
    contestName: "Design Challenge",
    contestBy: "John Doe",
  },
  {
    sl: 2,
    contestID: "DEF456",
    contestName: "Coding Competition",
    contestBy: "Jane Smith",
  },
  {
    sl: 3,
    contestID: "GHI789",
    contestName: "Art Contest",
    contestBy: "Alice Johnson",
  },
  {
    sl: 4,
    contestID: "JKL012",
    contestName: "Math Olympiad",
    contestBy: "Robert Brown",
  },
  {
    sl: 5,
    contestID: "MNO345",
    contestName: "Science Fair",
    contestBy: "Emily Wilson",
  },
  {
    sl: 6,
    contestID: "PQR678",
    contestName: "Music Competition",
    contestBy: "Michael Lee",
  },
  {
    sl: 7,
    contestID: "STU901",
    contestName: "Literature Contest",
    contestBy: "Sophia Martinez",
  },
  {
    sl: 8,
    contestID: "VWX234",
    contestName: "Chess Tournament",
    contestBy: "Daniel Taylor",
  },
  {
    sl: 9,
    contestID: "YZA567",
    contestName: "Spelling Bee",
    contestBy: "Olivia Garcia",
  },
  {
    sl: 10,
    contestID: "BCD890",
    contestName: "Debate Competition",
    contestBy: "William Clark",
  },
  {
    sl: 11,
    contestID: "EFG123",
    contestName: "Dance Contest",
    contestBy: "Ava White",
  },
  {
    sl: 12,
    contestID: "HIJ456",
    contestName: "Robotics Challenge",
    contestBy: "Ethan Hernandez",
  },
  {
    sl: 13,
    contestID: "KLM789",
    contestName: "Cooking Competition",
    contestBy: "Isabella Nguyen",
  },
  {
    sl: 14,
    contestID: "NOP012",
    contestName: "Film Festival",
    contestBy: "Noah King",
  },
  {
    sl: 15,
    contestID: "QRS345",
    contestName: "Fashion Show",
    contestBy: "Madison Baker",
  },
  {
    sl: 16,
    contestID: "TUV678",
    contestName: "Poetry Slam",
    contestBy: "David Scott",
  },
  {
    sl: 17,
    contestID: "WXY901",
    contestName: "Quiz Bowl",
    contestBy: "Lily Adams",
  },
  {
    sl: 18,
    contestID: "ZAB234",
    contestName: "Soccer Tournament",
    contestBy: "Elijah Carter",
  },
  {
    sl: 19,
    contestID: "CDE567",
    contestName: "Artificial Intelligence Challenge",
    contestBy: "Scarlett Cooper",
  },
  {
    sl: 20,
    contestID: "FGH890",
    contestName: "Hackathon",
    contestBy: "Gabriel Turner",
  },
];

export const singleContestDetails = {
  contestImage: "../assets/contest/image_00.png",
  contestBy: "johhny khan",
  category: "Sunset Tree",
  description:
    "In the tranquil embrace of the Sunset Tree, where shadows dance with the dying light, whispers of nostalgia weave through its branches, echoing tales of bygone days and promises of tomorrow's dawn.",
  rules: [
    "Specify theme.",
    "Specify theme.",
    "Specify theme.",
    "Specify theme.",
  ],
  votes: 3000,
  award: 5000,
  views: 1000,
  participants: 5000,
  price: 5000,
  time: "11h 31m 34s",
};
